### PR TITLE
Add support for creating "wildcard" and "regexp" queries

### LINKED ISSUE #15: Implement regexp_queries
### What did you do?
Want to use https://www.elastic.co/guide/en/elasticsearch/guide/current/_wildcard_and_regexp_queries.html

### What did you expect to happen?
```php
$queryBuilder->createRegexpQuery()
```
### What actually happened?

Fatal error

### What versions of PHP, Lumen and this module are you using?

PHP 5.6 ; Lumen 5.4

Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

### PR DESCRIPTION
**Pull request by Jalle19**
Closes #15

Changes proposed in this pull request:
 * Added support for wildcard and regexp queries

@michail1982 can you test this?

### CODE REVIEW

**Comment by kryysler** [comment]
@Jalle19 the queries does have some options that would be nice to support as well, see more at:

https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-regexp-query.html

 and

https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-wildcard-query.html

**Comment by kryysler** [comment]
Also, they are listed under "TermLevel" queries, so the namespace and folder structure could be updated to match that + add direct links to the manual (in last post)

**Comment by Jalle19** [comment]
@kryysler I went by the 5.x documentation where these things have been removed (or the documentation has been made shorter).

Similarly, in the 5.x documentation these types of queries are listed under "Partial matching".

**Comment by kryysler** [comment]
Hmm, ok. The project is built for ES 2.x and I think it won't run on 5.x without any hickups?

**Comment by Jalle19** [comment]
@kryysler my bad, I was looking at https://www.elastic.co/guide/en/elasticsearch/guide/current/_wildcard_and_regexp_queries.html which was mentioned in the issue. I'll rework the PR to include the missing options.

I'll code it against the v2.4 for now, but we should strongly consider supporting 5.x too.

**Comment by kryysler** [comment]
No worries. Yes, we should upgrade to 5.x asap.

**Comment by Jalle19** [comment]
Looking through the documentation again it seems both types of queries support `boost` while regexp queries also support `flags` and `max_determinized_states`.

**Comment by Jalle19** [comment]
@kryysler please re-review

**Comment by Jalle19** [comment]
> After moving the field to the base class, does the IDE understand the "(at)return $this" statement as the correct instance, so you can chain methods easily with autocompletion. Important as all queries does not have the same methods.

Yes, I tested this when writing tests. `@return $this` makes the IDE dynamically resolve the return value so it all works.

**Comment by Jalle19** [comment]
@kryysler done

**Pull request merged**
